// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package action

import (
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitGinAction(c *gin.Context) *GinAction {
	ginAction := NewGinAction(c)
	return ginAction
}
